/**
 * This file auto generated by script. Do not change it manually!!!
 * @see scripts/generateActionType.ts
 *
 */

/* eslint-disable */

import {createStandardAction, createAsyncAction} from 'typesafe-actions';

const ROOT_INITIALIZE_COMPLETE = '@ROOT/INITIALIZE_COMPLETE';
export const initializeCompleteCreator = createStandardAction(ROOT_INITIALIZE_COMPLETE);
const ROOT_INITIALIZE_FAIL = '@ROOT/INITIALIZE_FAIL';
export const initializeFailCreator = createStandardAction(ROOT_INITIALIZE_FAIL);
const ROOT_ERROR = '@ROOT/ERROR';
export const errorCreator = createStandardAction(ROOT_ERROR);
