/**
 * This file auto generated by script. Do not change it manually!!!
 * @see scripts/generateActionType.ts
 *
 */

/* eslint-disable */

import {createStandardAction, createAsyncAction} from 'typesafe-actions';

const NOTIFICATION_NOTIFY = '@NOTIFICATION/NOTIFY';
export const notifyCreator = createStandardAction(NOTIFICATION_NOTIFY);
